[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for proper MIME types
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"